name: Build XCFramework

on:
  push:
    tags:
      - 'M*-aac'
  workflow_dispatch:
    inputs:
      milestone:
        description: 'WebRTC Milestone (e.g., M143)'
        required: false
        default: 'current'

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        env:
          IOS_SDK_VERSION: "17.6"
        run: |
          set -euo pipefail

          SDK_NAME="iphoneos${IOS_SDK_VERSION}"
          echo "Searching for Xcode bundle that provides ${SDK_NAME}"

          FOUND_XCODE=""
          for XCODE_APP in /Applications/Xcode_*.app /Applications/Xcode.app; do
            [[ -d "$XCODE_APP" ]] || continue
            DEVELOPER_DIR="$XCODE_APP/Contents/Developer"
            if DEVELOPER_DIR="$DEVELOPER_DIR" xcodebuild -sdk "$SDK_NAME" -version >/dev/null 2>&1; then
              FOUND_XCODE="$XCODE_APP"
              break
            fi
          done

          if [[ -z "$FOUND_XCODE" ]]; then
            echo "::error::Unable to locate iOS SDK ${SDK_NAME} on this runner."
            xcodebuild -showsdks || true
            exit 1
          fi

          echo "Using $(basename "$FOUND_XCODE") for ${SDK_NAME}"
          sudo xcode-select -switch "$FOUND_XCODE"
          echo "IOS_SDK_VERSION=${IOS_SDK_VERSION}" >> "$GITHUB_ENV"
          echo "DEVELOPER_DIR=${FOUND_XCODE}/Contents/Developer" >> "$GITHUB_ENV"

      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: Verify Xcode and SDK
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo "Available SDKs:"
          xcodebuild -showsdks
          echo "Active iOS SDK (${IOS_SDK_VERSION}):"
          xcodebuild -sdk "iphoneos${IOS_SDK_VERSION}" -version
          echo "Developer directory:"
          echo $DEVELOPER_DIR

      - name: Sync WebRTC source
        run: |
          gclient sync --force

      - name: Apply AAC patches
        run: |
          ./scripts/apply_patches.sh

      - name: Detect Milestone
        id: milestone
        run: |
          MILESTONE=$(./scripts/detect_milestone.sh)
          echo "milestone=$MILESTONE" >> $GITHUB_OUTPUT
          echo "Detected Milestone: $MILESTONE"

      - name: Build XCFramework
        run: |
          export PATH="$PWD/depot_tools:$PATH"
          # Set environment variables to avoid module map issues
          export CXXFLAGS="-fno-modules -fno-objc-arc-errors"
          export CFLAGS="-fno-modules"
          # Keep deployment targets compatible across all bundled platforms
          export IOS_DEVICE_TARGET="13.0"
          export IOS_SIM_TARGET="13.0"
          export CATALYST_TARGET="14.0"
          export MAC_TARGET="11.0"
          ./scripts/build_all_configs.sh

      - name: Create archive
        id: archive
        run: |
          cd src
          MILESTONE="${{ steps.milestone.outputs.milestone }}"
          BUILD_NUM=$(git rev-list --count HEAD | tail -c 4)
          VERSION="${MILESTONE}.${BUILD_NUM}-aac"
          ARCHIVE_NAME="WebRTC-${VERSION}.xcframework.zip"

          ditto -c -k --sequesterRsrc --keepParent WebRTC.xcframework "$ARCHIVE_NAME"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "archive=$ARCHIVE_NAME" >> $GITHUB_OUTPUT
          echo "path=src/$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Calculate checksum
        id: checksum
        run: |
          cd src
          CHECKSUM=$(swift package compute-checksum "${{ steps.archive.outputs.archive }}")
          echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT
          echo "Checksum: $CHECKSUM"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework-${{ steps.milestone.outputs.milestone }}
          path: ${{ steps.archive.outputs.path }}
          retention-days: 30

    outputs:
      version: ${{ steps.archive.outputs.version }}
      archive: ${{ steps.archive.outputs.archive }}
      checksum: ${{ steps.checksum.outputs.checksum }}
      milestone: ${{ steps.milestone.outputs.milestone }}
